<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OLA.Business\OLA.Business.csproj" />
    <ProjectReference Include="..\OLA.Data\OLA.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\Loan\" />
    <None Remove="Models\request\Loan\" />
    <None Remove="Models\Filter\" />
    <None Remove="Models\response\" />
    <None Remove="Models\response\loan\" />
    <None Remove="Models\response\user\" />
    <None Remove="Extension\" />
    <None Remove="Extension\Account\" />
    <None Remove="Controllers\Administrator\" />
    <None Remove="Extension\Administrator\" />
    <None Remove="Models\Common\" />
    <None Remove="Models\request\Administrator\" />
    <None Remove="Models\response\Administrator\" />
    <None Remove="Models\Security\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\Loan\" />
    <Folder Include="Models\request\Loan\" />
    <Folder Include="Models\Filter\" />
    <Folder Include="Models\response\" />
    <Folder Include="Models\response\loan\" />
    <Folder Include="Models\response\user\" />
    <Folder Include="Extension\" />
    <Folder Include="Extension\Account\" />
    <Folder Include="Controllers\Administrator\" />
    <Folder Include="Extension\Administrator\" />
    <Folder Include="Models\Common\" />
    <Folder Include="Models\request\Administrator\" />
    <Folder Include="Models\response\Administrator\" />
    <Folder Include="Models\Security\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
    <Reference Include="System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  </ItemGroup>
</Project>
